Adding SimuLink and AutoSAR Metamodels
kit-sdq/DemoMetamodels pull request #23
Opened 2023-09-01 13:14 UTC by FabianEger

2023-09-01 13:58 UTC, TomWerm requested changes

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/META-INF/MANIFEST.MF
> +Bundle-Version: 0.1.0.qualifier
```suggestion
Bundle-Version: 1.8.0.qualifier
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/META-INF/MANIFEST.MF
> +Bundle-RequiredExecutionEnvironment: J2SE-1.5
```suggestion
Bundle-RequiredExecutionEnvironment: JavaSE-17

```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/META-INF/MANIFEST.MF
> +Bundle-SymbolicName: AutoSAR;singleton:=true
```suggestion
Bundle-SymbolicName: edu.kit.ipd.sdq.metamodels.autosar;singleton:=true

```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/META-INF/MANIFEST.MF
> +Automatic-Module-Name: AutoSAR
```suggestion
Automatic-Module-Name: edu.kit.ipd.sdq.metamodels.autosar
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/build.properties
> +output.. = bin/
```suggestion
output.. = target/classes/
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/plugin.properties
> +providerName = www.example.org
```suggestion
providerName = KIT SDQ
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/plugin.properties
> +pluginName = AutoSAR
```suggestion
pluginName = AutoSAR Metamodel
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/plugin.xml
> +            uri="http://www.example.org/autoSAR"
```suggestion
            uri="edu.kit.ipd.sdq.metamodels.autosar"
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/plugin.xml
> +            class="autoSAR.AutoSARPackage"
```suggestion
            class="edu.kit.ipd.sdq.metamodels.autosar.AutoSARPackage"

```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/META-INF/MANIFEST.MF
> +Bundle-SymbolicName: SimuLink;singleton:=true
```suggestion
Bundle-SymbolicName: edu.kit.ipd.sdq.metamodels.simulink;singleton:=true
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/META-INF/MANIFEST.MF
> +Automatic-Module-Name: SimuLink
```suggestion
Automatic-Module-Name: edu.kit.ipd.sdq.metamodels.simulink
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/META-INF/MANIFEST.MF
> +Bundle-Version: 0.1.0.qualifier
```suggestion
Bundle-Version: 1.8.0.qualifier
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/META-INF/MANIFEST.MF
> +Bundle-RequiredExecutionEnvironment: J2SE-1.5
```suggestion
Bundle-RequiredExecutionEnvironment: JavaSE-17
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/build.properties
> +output.. = bin/
```suggestion
output.. = target/classes/
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/model/simuLink.aird
.aird files contain the visual representation and can be omitted, so I suggest to also omit them (as they can be generated again if needed).

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/model/autoSAR.aird
omit, see other comment regarding .aird

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/plugin.properties
> +providerName = www.example.org
```suggestion
providerName = KIT SDQ
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/plugin.properties
> +pluginName = SimuLink
```suggestion
pluginName = SimuLink Metamodel
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/plugin.xml
> +            uri="http://hu.bme.mit.massif/simulink/1.0"
```suggestion
            <!-- source uri="http://hu.bme.mit.massif/simulink/1.0" adapted for usage in Vitruvius (vitruv.tools) context -->
            uri="edu.kit.ipd.sdq.metamodels.simulink"
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/plugin.xml
> +            class="simulink.SimuLinkPackage"
```suggestion
            class="edu.kit.ipd.sdq.metamodels.simulink.SimuLinkPackage"

```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/model/autoSAR.ecore
> +    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="autoSAR" nsURI="http://www.example.org/autoSAR" nsPrefix="autoSAR">
```suggestion
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="autoSAR" nsURI="edu.kit.ipd.sdq.metamodels.autoSAR" nsPrefix="autoSAR">
```

2023-09-01 13:58 UTC, TomWerm commented on bundles/edu.kit.ipd.sdq.metamodels.simulink/model/simuLink.ecore
> +    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulink" nsURI="http://hu.bme.mit.massif/simulink/1.0" nsPrefix="simulink">
```suggestion
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulink" nsURI="edu.kit.ipd.sdq.metamodels.simulink" nsPrefix="simulink">
```

2023-09-01 13:58 UTC, TomWerm commented on features/edu.kit.ipd.sdq.metamodels.autosar.feature/feature.properties
> +Copyright (c) 2014-2020 SDQ\n\
```suggestion
Copyright (c) 2014-2023 SDQ\n\
```

2023-09-01 13:58 UTC, TomWerm commented on features/edu.kit.ipd.sdq.metamodels.autosar.feature/feature.xml
> +         id="edu.kit.ipd.sdq.metamodels.autosar"
Consistent everywhere AutoSAR or autosar (I prefer the second one)

2023-09-01 13:58 UTC, TomWerm commented on features/edu.kit.ipd.sdq.metamodels.simulink.feature/feature.properties
> +Copyright (c) 2014-2020 SDQ\n\
```suggestion
Copyright (c) 2014-2023 SDQ\n\
```

2023-09-01 14:06 UTC, FabianEger commented on bundles/edu.kit.ipd.sdq.metamodels.autosar/model/autoSAR.ecore
> +    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="autoSAR" nsURI="http://www.example.org/autoSAR" nsPrefix="autoSAR">
without addresses

2023-09-01 14:22 UTC, FabianEger reviewed
changed the requested changes from the review

2023-09-04 10:21 UTC, TomWerm approved these changes

2023-09-04 10:21 UTC, merged